// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID              int32                 `json:"id"`
	ActorEmail      string                `json:"actor_email"`
	Action          string                `json:"action"`
	TargetCompanyID uuid.NullUUID         `json:"target_company_id"`
	Details         pqtype.NullRawMessage `json:"details"`
	CreatedAt       sql.NullTime          `json:"created_at"`
}

type Company struct {
	ID                 uuid.UUID      `json:"id"`
	Name               sql.NullString `json:"name"`
	AdminEmail         string         `json:"admin_email"`
	AdminPasswordHash  sql.NullString `json:"admin_password_hash"`
	WhatsappPhone      sql.NullString `json:"whatsapp_phone"`
	LogoUrl            sql.NullString `json:"logo_url"`
	BrandColor         sql.NullString `json:"brand_color"`
	AuthStatus         sql.NullString `json:"auth_status"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionExpiry sql.NullTime   `json:"subscription_expiry"`
	PlanType           sql.NullString `json:"plan_type"`
	SetupToken         sql.NullString `json:"setup_token"`
	TrackingPrefix     sql.NullString `json:"tracking_prefix"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type Groupauthority struct {
	CompanyID    uuid.UUID    `json:"company_id"`
	Jid          string       `json:"jid"`
	IsAuthorized bool         `json:"is_authorized"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Payment struct {
	ID        int32           `json:"id"`
	CompanyID uuid.NullUUID   `json:"company_id"`
	Reference string          `json:"reference"`
	Amount    sql.NullFloat64 `json:"amount"`
	Status    sql.NullString  `json:"status"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Plan struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	NameKey     string          `json:"name_key"`
	DescKey     string          `json:"desc_key"`
	BasePrice   int32           `json:"base_price"`
	Currency    string          `json:"currency"`
	IntervalKey string          `json:"interval_key"`
	Popular     sql.NullBool    `json:"popular"`
	TrialKey    sql.NullString  `json:"trial_key"`
	BtnKey      string          `json:"btn_key"`
	Features    json.RawMessage `json:"features"`
	IsActive    sql.NullBool    `json:"is_active"`
	SortOrder   sql.NullInt32   `json:"sort_order"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type Shipment struct {
	TrackingID           string          `json:"tracking_id"`
	CompanyID            uuid.NullUUID   `json:"company_id"`
	UserJid              string          `json:"user_jid"`
	Status               sql.NullString  `json:"status"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	ScheduledTransitTime sql.NullTime    `json:"scheduled_transit_time"`
	OutfordeliveryTime   sql.NullTime    `json:"outfordelivery_time"`
	ExpectedDeliveryTime sql.NullTime    `json:"expected_delivery_time"`
	SenderTimezone       sql.NullString  `json:"sender_timezone"`
	RecipientTimezone    sql.NullString  `json:"recipient_timezone"`
	SenderName           sql.NullString  `json:"sender_name"`
	SenderPhone          sql.NullString  `json:"sender_phone"`
	Origin               sql.NullString  `json:"origin"`
	RecipientName        sql.NullString  `json:"recipient_name"`
	RecipientPhone       sql.NullString  `json:"recipient_phone"`
	RecipientEmail       sql.NullString  `json:"recipient_email"`
	RecipientID          sql.NullString  `json:"recipient_id"`
	RecipientAddress     sql.NullString  `json:"recipient_address"`
	Destination          sql.NullString  `json:"destination"`
	CargoType            sql.NullString  `json:"cargo_type"`
	Weight               sql.NullFloat64 `json:"weight"`
	Cost                 sql.NullFloat64 `json:"cost"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}

type Systemconfig struct {
	CompanyID uuid.UUID    `json:"company_id"`
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Telemetry struct {
	ID        int32                 `json:"id"`
	CompanyID uuid.NullUUID         `json:"company_id"`
	EventType string                `json:"event_type"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Userpreference struct {
	CompanyID uuid.UUID    `json:"company_id"`
	Jid       string       `json:"jid"`
	Language  string       `json:"language"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
