// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	BulkDeleteShipments(ctx context.Context, arg BulkDeleteShipmentsParams) (sql.Result, error)
	BulkUpdateStatus(ctx context.Context, arg BulkUpdateStatusParams) error
	CountAuthorizedGroups(ctx context.Context, companyID uuid.UUID) (int64, error)
	CountCreatedSince(ctx context.Context, arg CountCreatedSinceParams) (int64, error)
	CountDeliveredSince(ctx context.Context, arg CountDeliveredSinceParams) (int64, error)
	CountShipments(ctx context.Context, companyID uuid.NullUUID) (int64, error)
	CountShipmentsByStatus(ctx context.Context, companyID uuid.NullUUID) (CountShipmentsByStatusRow, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) error
	DeleteDeliveredShipments(ctx context.Context, companyID uuid.NullUUID) error
	DeleteShipment(ctx context.Context, arg DeleteShipmentParams) error
	FindSimilarShipment(ctx context.Context, arg FindSimilarShipmentParams) (string, error)
	GetActivePlans(ctx context.Context) ([]GetActivePlansRow, error)
	GetAllActiveCompanies(ctx context.Context) ([]Company, error)
	GetAllCompanies(ctx context.Context) ([]uuid.UUID, error)
	GetAuthorizedGroups(ctx context.Context, companyID uuid.UUID) ([]string, error)
	GetCompanyByEmail(ctx context.Context, adminEmail string) (Company, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error)
	GetGroupAuthority(ctx context.Context, arg GetGroupAuthorityParams) (GetGroupAuthorityRow, error)
	GetLastShipmentIDForUser(ctx context.Context, arg GetLastShipmentIDForUserParams) (string, error)
	GetPlanByID(ctx context.Context, id string) (GetPlanByIDRow, error)
	GetRecentEvents(ctx context.Context, arg GetRecentEventsParams) ([]Telemetry, error)
	GetShipment(ctx context.Context, arg GetShipmentParams) (Shipment, error)
	GetSystemConfig(ctx context.Context, arg GetSystemConfigParams) (string, error)
	GetTelemetryStats(ctx context.Context, arg GetTelemetryStatsParams) ([]GetTelemetryStatsRow, error)
	GetUserLanguage(ctx context.Context, arg GetUserLanguageParams) (string, error)
	HasAuthorizedGroups(ctx context.Context, companyID uuid.UUID) (int64, error)
	ListAllShipments(ctx context.Context, companyID uuid.NullUUID) ([]Shipment, error)
	ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error)
	RecordEvent(ctx context.Context, arg RecordEventParams) error
	RecordPayment(ctx context.Context, arg RecordPaymentParams) (int32, error)
	RunAgedCleanup(ctx context.Context, arg RunAgedCleanupParams) (sql.Result, error)
	SetCompanyPassword(ctx context.Context, arg SetCompanyPasswordParams) error
	SetGroupAuthority(ctx context.Context, arg SetGroupAuthorityParams) error
	SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) error
	SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error
	TransitionStatusToDelivered(ctx context.Context, arg TransitionStatusToDeliveredParams) ([]TransitionStatusToDeliveredRow, error)
	TransitionStatusToIntransit(ctx context.Context, arg TransitionStatusToIntransitParams) ([]TransitionStatusToIntransitRow, error)
	TransitionStatusToOutForDelivery(ctx context.Context, arg TransitionStatusToOutForDeliveryParams) ([]TransitionStatusToOutForDeliveryRow, error)
	UpdateCompanyAuthStatus(ctx context.Context, arg UpdateCompanyAuthStatusParams) error
	UpdateCompanyOnboarding(ctx context.Context, arg UpdateCompanyOnboardingParams) error
	UpdateCompanySettings(ctx context.Context, arg UpdateCompanySettingsParams) error
	UpdateCompanySubscriptionStatus(ctx context.Context, arg UpdateCompanySubscriptionStatusParams) error
	UpdatePlanPrice(ctx context.Context, arg UpdatePlanPriceParams) error
	UpdateShipmentDynamic(ctx context.Context, arg UpdateShipmentDynamicParams) error
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) error
}

var _ Querier = (*Queries)(nil)
