// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const bulkDeleteShipments = `-- name: BulkDeleteShipments :execresult
DELETE FROM Shipment WHERE company_id = $1 AND tracking_id = ANY($2::text[])
`

type BulkDeleteShipmentsParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	Column2   []string      `json:"column_2"`
}

func (q *Queries) BulkDeleteShipments(ctx context.Context, arg BulkDeleteShipmentsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, bulkDeleteShipments, arg.CompanyID, pq.Array(arg.Column2))
}

const bulkUpdateStatus = `-- name: BulkUpdateStatus :exec
UPDATE Shipment
SET status = $3, updated_at = CURRENT_TIMESTAMP
WHERE company_id = $1 AND tracking_id = ANY($2::text[])
`

type BulkUpdateStatusParams struct {
	CompanyID uuid.NullUUID  `json:"company_id"`
	Column2   []string       `json:"column_2"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) BulkUpdateStatus(ctx context.Context, arg BulkUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateStatus, arg.CompanyID, pq.Array(arg.Column2), arg.Status)
	return err
}

const countAuthorizedGroups = `-- name: CountAuthorizedGroups :one
SELECT COUNT(*) FROM GroupAuthority WHERE company_id = $1 AND is_authorized = true
`

func (q *Queries) CountAuthorizedGroups(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthorizedGroups, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCreatedSince = `-- name: CountCreatedSince :one
SELECT COUNT(*) FROM Shipment WHERE company_id = $1 AND created_at >= $2
`

type CountCreatedSinceParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

func (q *Queries) CountCreatedSince(ctx context.Context, arg CountCreatedSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCreatedSince, arg.CompanyID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveredSince = `-- name: CountDeliveredSince :one
SELECT COUNT(*) FROM Shipment WHERE company_id = $1 AND status = 'delivered' AND updated_at >= $2
`

type CountDeliveredSinceParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

func (q *Queries) CountDeliveredSince(ctx context.Context, arg CountDeliveredSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveredSince, arg.CompanyID, arg.UpdatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipments = `-- name: CountShipments :one
SELECT COUNT(*) FROM Shipment WHERE company_id = $1
`

func (q *Queries) CountShipments(ctx context.Context, companyID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShipments, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipmentsByStatus = `-- name: CountShipmentsByStatus :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE status = 'intransit') AS intransit,
    COUNT(*) FILTER (WHERE status = 'outfordelivery') AS outfordelivery,
    COUNT(*) FILTER (WHERE status = 'delivered') AS delivered,
    COUNT(*) FILTER (WHERE status = 'canceled') AS canceled
FROM Shipment WHERE company_id = $1
`

type CountShipmentsByStatusRow struct {
	Total          int64 `json:"total"`
	Pending        int64 `json:"pending"`
	Intransit      int64 `json:"intransit"`
	Outfordelivery int64 `json:"outfordelivery"`
	Delivered      int64 `json:"delivered"`
	Canceled       int64 `json:"canceled"`
}

func (q *Queries) CountShipmentsByStatus(ctx context.Context, companyID uuid.NullUUID) (CountShipmentsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countShipmentsByStatus, companyID)
	var i CountShipmentsByStatusRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Intransit,
		&i.Outfordelivery,
		&i.Delivered,
		&i.Canceled,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, admin_email, setup_token, subscription_expiry, plan_type) 
VALUES ($1, $2, $3, CURRENT_TIMESTAMP + INTERVAL '7 days', 'trial') 
RETURNING id, name, admin_email, admin_password_hash, whatsapp_phone, logo_url, brand_color, auth_status, subscription_status, subscription_expiry, plan_type, setup_token, tracking_prefix, created_at, updated_at
`

type CreateCompanyParams struct {
	Name       sql.NullString `json:"name"`
	AdminEmail string         `json:"admin_email"`
	SetupToken sql.NullString `json:"setup_token"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Name, arg.AdminEmail, arg.SetupToken)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminEmail,
		&i.AdminPasswordHash,
		&i.WhatsappPhone,
		&i.LogoUrl,
		&i.BrandColor,
		&i.AuthStatus,
		&i.SubscriptionStatus,
		&i.SubscriptionExpiry,
		&i.PlanType,
		&i.SetupToken,
		&i.TrackingPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :exec
INSERT INTO Shipment (
    company_id, tracking_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
)
`

type CreateShipmentParams struct {
	CompanyID            uuid.NullUUID   `json:"company_id"`
	TrackingID           string          `json:"tracking_id"`
	UserJid              string          `json:"user_jid"`
	Status               sql.NullString  `json:"status"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	ScheduledTransitTime sql.NullTime    `json:"scheduled_transit_time"`
	OutfordeliveryTime   sql.NullTime    `json:"outfordelivery_time"`
	ExpectedDeliveryTime sql.NullTime    `json:"expected_delivery_time"`
	SenderTimezone       sql.NullString  `json:"sender_timezone"`
	RecipientTimezone    sql.NullString  `json:"recipient_timezone"`
	SenderName           sql.NullString  `json:"sender_name"`
	SenderPhone          sql.NullString  `json:"sender_phone"`
	Origin               sql.NullString  `json:"origin"`
	RecipientName        sql.NullString  `json:"recipient_name"`
	RecipientPhone       sql.NullString  `json:"recipient_phone"`
	RecipientEmail       sql.NullString  `json:"recipient_email"`
	RecipientID          sql.NullString  `json:"recipient_id"`
	RecipientAddress     sql.NullString  `json:"recipient_address"`
	Destination          sql.NullString  `json:"destination"`
	CargoType            sql.NullString  `json:"cargo_type"`
	Weight               sql.NullFloat64 `json:"weight"`
	Cost                 sql.NullFloat64 `json:"cost"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) error {
	_, err := q.db.ExecContext(ctx, createShipment,
		arg.CompanyID,
		arg.TrackingID,
		arg.UserJid,
		arg.Status,
		arg.CreatedAt,
		arg.ScheduledTransitTime,
		arg.OutfordeliveryTime,
		arg.ExpectedDeliveryTime,
		arg.SenderTimezone,
		arg.RecipientTimezone,
		arg.SenderName,
		arg.SenderPhone,
		arg.Origin,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.RecipientEmail,
		arg.RecipientID,
		arg.RecipientAddress,
		arg.Destination,
		arg.CargoType,
		arg.Weight,
		arg.Cost,
		arg.UpdatedAt,
	)
	return err
}

const deleteDeliveredShipments = `-- name: DeleteDeliveredShipments :exec
DELETE FROM Shipment WHERE company_id = $1 AND status = 'delivered'
`

func (q *Queries) DeleteDeliveredShipments(ctx context.Context, companyID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveredShipments, companyID)
	return err
}

const deleteShipment = `-- name: DeleteShipment :exec
DELETE FROM Shipment WHERE company_id = $1 AND tracking_id = $2
`

type DeleteShipmentParams struct {
	CompanyID  uuid.NullUUID `json:"company_id"`
	TrackingID string        `json:"tracking_id"`
}

func (q *Queries) DeleteShipment(ctx context.Context, arg DeleteShipmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteShipment, arg.CompanyID, arg.TrackingID)
	return err
}

const findSimilarShipment = `-- name: FindSimilarShipment :one
SELECT tracking_id FROM Shipment 
WHERE company_id = $1 AND user_jid = $2 AND recipient_phone = $3 AND $3 != ''
ORDER BY created_at DESC LIMIT 1
`

type FindSimilarShipmentParams struct {
	CompanyID      uuid.NullUUID  `json:"company_id"`
	UserJid        string         `json:"user_jid"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
}

func (q *Queries) FindSimilarShipment(ctx context.Context, arg FindSimilarShipmentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findSimilarShipment, arg.CompanyID, arg.UserJid, arg.RecipientPhone)
	var tracking_id string
	err := row.Scan(&tracking_id)
	return tracking_id, err
}

const getActivePlans = `-- name: GetActivePlans :many
SELECT id, name, name_key, desc_key, base_price, currency, interval_key, popular, trial_key, btn_key, features, sort_order
FROM plans
WHERE is_active = TRUE
ORDER BY sort_order ASC
`

type GetActivePlansRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	NameKey     string          `json:"name_key"`
	DescKey     string          `json:"desc_key"`
	BasePrice   int32           `json:"base_price"`
	Currency    string          `json:"currency"`
	IntervalKey string          `json:"interval_key"`
	Popular     sql.NullBool    `json:"popular"`
	TrialKey    sql.NullString  `json:"trial_key"`
	BtnKey      string          `json:"btn_key"`
	Features    json.RawMessage `json:"features"`
	SortOrder   sql.NullInt32   `json:"sort_order"`
}

func (q *Queries) GetActivePlans(ctx context.Context) ([]GetActivePlansRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePlansRow
	for rows.Next() {
		var i GetActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.DescKey,
			&i.BasePrice,
			&i.Currency,
			&i.IntervalKey,
			&i.Popular,
			&i.TrialKey,
			&i.BtnKey,
			&i.Features,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveCompanies = `-- name: GetAllActiveCompanies :many
SELECT id, name, admin_email, admin_password_hash, whatsapp_phone, logo_url, brand_color, auth_status, subscription_status, subscription_expiry, plan_type, setup_token, tracking_prefix, created_at, updated_at FROM companies 
WHERE auth_status = 'active' 
  AND subscription_status IN ('active', 'trialing')
  AND (subscription_expiry IS NULL OR subscription_expiry > CURRENT_TIMESTAMP)
`

func (q *Queries) GetAllActiveCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdminEmail,
			&i.AdminPasswordHash,
			&i.WhatsappPhone,
			&i.LogoUrl,
			&i.BrandColor,
			&i.AuthStatus,
			&i.SubscriptionStatus,
			&i.SubscriptionExpiry,
			&i.PlanType,
			&i.SetupToken,
			&i.TrackingPrefix,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCompanies = `-- name: GetAllCompanies :many
SELECT id FROM companies
`

func (q *Queries) GetAllCompanies(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorizedGroups = `-- name: GetAuthorizedGroups :many
SELECT jid FROM GroupAuthority WHERE company_id = $1 AND is_authorized = true
`

func (q *Queries) GetAuthorizedGroups(ctx context.Context, companyID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorizedGroups, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jid string
		if err := rows.Scan(&jid); err != nil {
			return nil, err
		}
		items = append(items, jid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanyByEmail = `-- name: GetCompanyByEmail :one
SELECT id, name, admin_email, admin_password_hash, whatsapp_phone, logo_url, brand_color, auth_status, subscription_status, subscription_expiry, plan_type, setup_token, tracking_prefix, created_at, updated_at FROM companies WHERE admin_email = $1
`

func (q *Queries) GetCompanyByEmail(ctx context.Context, adminEmail string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByEmail, adminEmail)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminEmail,
		&i.AdminPasswordHash,
		&i.WhatsappPhone,
		&i.LogoUrl,
		&i.BrandColor,
		&i.AuthStatus,
		&i.SubscriptionStatus,
		&i.SubscriptionExpiry,
		&i.PlanType,
		&i.SetupToken,
		&i.TrackingPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, admin_email, admin_password_hash, whatsapp_phone, logo_url, brand_color, auth_status, subscription_status, subscription_expiry, plan_type, setup_token, tracking_prefix, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminEmail,
		&i.AdminPasswordHash,
		&i.WhatsappPhone,
		&i.LogoUrl,
		&i.BrandColor,
		&i.AuthStatus,
		&i.SubscriptionStatus,
		&i.SubscriptionExpiry,
		&i.PlanType,
		&i.SetupToken,
		&i.TrackingPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupAuthority = `-- name: GetGroupAuthority :one
SELECT is_authorized, updated_at FROM GroupAuthority WHERE company_id = $1 AND jid = $2
`

type GetGroupAuthorityParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Jid       string    `json:"jid"`
}

type GetGroupAuthorityRow struct {
	IsAuthorized bool         `json:"is_authorized"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetGroupAuthority(ctx context.Context, arg GetGroupAuthorityParams) (GetGroupAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupAuthority, arg.CompanyID, arg.Jid)
	var i GetGroupAuthorityRow
	err := row.Scan(&i.IsAuthorized, &i.UpdatedAt)
	return i, err
}

const getLastShipmentIDForUser = `-- name: GetLastShipmentIDForUser :one
SELECT tracking_id FROM Shipment WHERE company_id = $1 AND user_jid = $2 ORDER BY created_at DESC LIMIT 1
`

type GetLastShipmentIDForUserParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	UserJid   string        `json:"user_jid"`
}

func (q *Queries) GetLastShipmentIDForUser(ctx context.Context, arg GetLastShipmentIDForUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastShipmentIDForUser, arg.CompanyID, arg.UserJid)
	var tracking_id string
	err := row.Scan(&tracking_id)
	return tracking_id, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, name_key, desc_key, base_price, currency, interval_key, popular, trial_key, btn_key, features
FROM plans
WHERE id = $1 AND is_active = TRUE
`

type GetPlanByIDRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	NameKey     string          `json:"name_key"`
	DescKey     string          `json:"desc_key"`
	BasePrice   int32           `json:"base_price"`
	Currency    string          `json:"currency"`
	IntervalKey string          `json:"interval_key"`
	Popular     sql.NullBool    `json:"popular"`
	TrialKey    sql.NullString  `json:"trial_key"`
	BtnKey      string          `json:"btn_key"`
	Features    json.RawMessage `json:"features"`
}

func (q *Queries) GetPlanByID(ctx context.Context, id string) (GetPlanByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlanByID, id)
	var i GetPlanByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.DescKey,
		&i.BasePrice,
		&i.Currency,
		&i.IntervalKey,
		&i.Popular,
		&i.TrialKey,
		&i.BtnKey,
		&i.Features,
	)
	return i, err
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, company_id, event_type, metadata, created_at FROM Telemetry
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentEventsParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	Limit     int32         `json:"limit"`
}

func (q *Queries) GetRecentEvents(ctx context.Context, arg GetRecentEventsParams) ([]Telemetry, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Telemetry
	for rows.Next() {
		var i Telemetry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShipment = `-- name: GetShipment :one
SELECT tracking_id, company_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at FROM Shipment WHERE company_id = $1 AND tracking_id = $2
`

type GetShipmentParams struct {
	CompanyID  uuid.NullUUID `json:"company_id"`
	TrackingID string        `json:"tracking_id"`
}

func (q *Queries) GetShipment(ctx context.Context, arg GetShipmentParams) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, getShipment, arg.CompanyID, arg.TrackingID)
	var i Shipment
	err := row.Scan(
		&i.TrackingID,
		&i.CompanyID,
		&i.UserJid,
		&i.Status,
		&i.CreatedAt,
		&i.ScheduledTransitTime,
		&i.OutfordeliveryTime,
		&i.ExpectedDeliveryTime,
		&i.SenderTimezone,
		&i.RecipientTimezone,
		&i.SenderName,
		&i.SenderPhone,
		&i.Origin,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientEmail,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.Destination,
		&i.CargoType,
		&i.Weight,
		&i.Cost,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT value FROM SystemConfig WHERE company_id = $1 AND key = $2
`

type GetSystemConfigParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Key       string    `json:"key"`
}

func (q *Queries) GetSystemConfig(ctx context.Context, arg GetSystemConfigParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSystemConfig, arg.CompanyID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getTelemetryStats = `-- name: GetTelemetryStats :many
SELECT event_type, COUNT(*) as count
FROM Telemetry
WHERE company_id = $1 AND created_at >= $2
GROUP BY event_type
`

type GetTelemetryStatsParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type GetTelemetryStatsRow struct {
	EventType string `json:"event_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetTelemetryStats(ctx context.Context, arg GetTelemetryStatsParams) ([]GetTelemetryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTelemetryStats, arg.CompanyID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryStatsRow
	for rows.Next() {
		var i GetTelemetryStatsRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLanguage = `-- name: GetUserLanguage :one
SELECT language FROM UserPreference WHERE company_id = $1 AND jid = $2
`

type GetUserLanguageParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Jid       string    `json:"jid"`
}

func (q *Queries) GetUserLanguage(ctx context.Context, arg GetUserLanguageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserLanguage, arg.CompanyID, arg.Jid)
	var language string
	err := row.Scan(&language)
	return language, err
}

const hasAuthorizedGroups = `-- name: HasAuthorizedGroups :one
SELECT COUNT(*) FROM GroupAuthority WHERE company_id = $1 AND is_authorized = true
`

func (q *Queries) HasAuthorizedGroups(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAuthorizedGroups, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllShipments = `-- name: ListAllShipments :many
SELECT tracking_id, company_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at FROM Shipment WHERE company_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAllShipments(ctx context.Context, companyID uuid.NullUUID) ([]Shipment, error) {
	rows, err := q.db.QueryContext(ctx, listAllShipments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.TrackingID,
			&i.CompanyID,
			&i.UserJid,
			&i.Status,
			&i.CreatedAt,
			&i.ScheduledTransitTime,
			&i.OutfordeliveryTime,
			&i.ExpectedDeliveryTime,
			&i.SenderTimezone,
			&i.RecipientTimezone,
			&i.SenderName,
			&i.SenderPhone,
			&i.Origin,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.RecipientEmail,
			&i.RecipientID,
			&i.RecipientAddress,
			&i.Destination,
			&i.CargoType,
			&i.Weight,
			&i.Cost,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT tracking_id, company_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at FROM Shipment WHERE company_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListShipmentsParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error) {
	rows, err := q.db.QueryContext(ctx, listShipments, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.TrackingID,
			&i.CompanyID,
			&i.UserJid,
			&i.Status,
			&i.CreatedAt,
			&i.ScheduledTransitTime,
			&i.OutfordeliveryTime,
			&i.ExpectedDeliveryTime,
			&i.SenderTimezone,
			&i.RecipientTimezone,
			&i.SenderName,
			&i.SenderPhone,
			&i.Origin,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.RecipientEmail,
			&i.RecipientID,
			&i.RecipientAddress,
			&i.Destination,
			&i.CargoType,
			&i.Weight,
			&i.Cost,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :exec
INSERT INTO Telemetry (company_id, event_type, metadata, created_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
`

type RecordEventParams struct {
	CompanyID uuid.NullUUID         `json:"company_id"`
	EventType string                `json:"event_type"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.ExecContext(ctx, recordEvent, arg.CompanyID, arg.EventType, arg.Metadata)
	return err
}

const recordPayment = `-- name: RecordPayment :one
INSERT INTO payments (company_id, reference, amount, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (reference) DO NOTHING
RETURNING id
`

type RecordPaymentParams struct {
	CompanyID uuid.NullUUID   `json:"company_id"`
	Reference string          `json:"reference"`
	Amount    sql.NullFloat64 `json:"amount"`
	Status    sql.NullString  `json:"status"`
}

func (q *Queries) RecordPayment(ctx context.Context, arg RecordPaymentParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, recordPayment,
		arg.CompanyID,
		arg.Reference,
		arg.Amount,
		arg.Status,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const runAgedCleanup = `-- name: RunAgedCleanup :execresult
DELETE FROM Shipment 
WHERE company_id = $1 AND ((status = 'delivered' AND updated_at < $2) OR (created_at < $3))
`

type RunAgedCleanupParams struct {
	CompanyID uuid.NullUUID `json:"company_id"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

func (q *Queries) RunAgedCleanup(ctx context.Context, arg RunAgedCleanupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, runAgedCleanup, arg.CompanyID, arg.UpdatedAt, arg.CreatedAt)
}

const setCompanyPassword = `-- name: SetCompanyPassword :exec
UPDATE companies SET admin_password_hash = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type SetCompanyPasswordParams struct {
	ID                uuid.UUID      `json:"id"`
	AdminPasswordHash sql.NullString `json:"admin_password_hash"`
}

func (q *Queries) SetCompanyPassword(ctx context.Context, arg SetCompanyPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setCompanyPassword, arg.ID, arg.AdminPasswordHash)
	return err
}

const setGroupAuthority = `-- name: SetGroupAuthority :exec
INSERT INTO GroupAuthority (company_id, jid, is_authorized, updated_at) 
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT(company_id, jid) DO UPDATE SET is_authorized = EXCLUDED.is_authorized, updated_at = CURRENT_TIMESTAMP
`

type SetGroupAuthorityParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	Jid          string    `json:"jid"`
	IsAuthorized bool      `json:"is_authorized"`
}

func (q *Queries) SetGroupAuthority(ctx context.Context, arg SetGroupAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, setGroupAuthority, arg.CompanyID, arg.Jid, arg.IsAuthorized)
	return err
}

const setSystemConfig = `-- name: SetSystemConfig :exec
INSERT INTO SystemConfig (company_id, key, value, updated_at) 
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT(company_id, key) DO UPDATE SET value = EXCLUDED.value, updated_at = CURRENT_TIMESTAMP
`

type SetSystemConfigParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
}

func (q *Queries) SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) error {
	_, err := q.db.ExecContext(ctx, setSystemConfig, arg.CompanyID, arg.Key, arg.Value)
	return err
}

const setUserLanguage = `-- name: SetUserLanguage :exec
INSERT INTO UserPreference (company_id, jid, language, updated_at) 
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT(company_id, jid) DO UPDATE SET language = EXCLUDED.language, updated_at = CURRENT_TIMESTAMP
`

type SetUserLanguageParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Jid       string    `json:"jid"`
	Language  string    `json:"language"`
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.ExecContext(ctx, setUserLanguage, arg.CompanyID, arg.Jid, arg.Language)
	return err
}

const transitionStatusToDelivered = `-- name: TransitionStatusToDelivered :many
UPDATE Shipment
SET status = 'delivered', updated_at = CURRENT_TIMESTAMP
WHERE company_id = $1 AND status = 'outfordelivery' AND expected_delivery_time <= $2
RETURNING tracking_id, status AS new_status, user_jid, recipient_email
`

type TransitionStatusToDeliveredParams struct {
	CompanyID            uuid.NullUUID `json:"company_id"`
	ExpectedDeliveryTime sql.NullTime  `json:"expected_delivery_time"`
}

type TransitionStatusToDeliveredRow struct {
	TrackingID     string         `json:"tracking_id"`
	NewStatus      sql.NullString `json:"new_status"`
	UserJid        string         `json:"user_jid"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) TransitionStatusToDelivered(ctx context.Context, arg TransitionStatusToDeliveredParams) ([]TransitionStatusToDeliveredRow, error) {
	rows, err := q.db.QueryContext(ctx, transitionStatusToDelivered, arg.CompanyID, arg.ExpectedDeliveryTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionStatusToDeliveredRow
	for rows.Next() {
		var i TransitionStatusToDeliveredRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.NewStatus,
			&i.UserJid,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionStatusToIntransit = `-- name: TransitionStatusToIntransit :many
UPDATE Shipment
SET status = 'intransit', updated_at = CURRENT_TIMESTAMP
WHERE company_id = $1 AND status = 'pending' AND scheduled_transit_time <= $2
RETURNING tracking_id, status AS new_status, user_jid, recipient_email
`

type TransitionStatusToIntransitParams struct {
	CompanyID            uuid.NullUUID `json:"company_id"`
	ScheduledTransitTime sql.NullTime  `json:"scheduled_transit_time"`
}

type TransitionStatusToIntransitRow struct {
	TrackingID     string         `json:"tracking_id"`
	NewStatus      sql.NullString `json:"new_status"`
	UserJid        string         `json:"user_jid"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) TransitionStatusToIntransit(ctx context.Context, arg TransitionStatusToIntransitParams) ([]TransitionStatusToIntransitRow, error) {
	rows, err := q.db.QueryContext(ctx, transitionStatusToIntransit, arg.CompanyID, arg.ScheduledTransitTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionStatusToIntransitRow
	for rows.Next() {
		var i TransitionStatusToIntransitRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.NewStatus,
			&i.UserJid,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionStatusToOutForDelivery = `-- name: TransitionStatusToOutForDelivery :many
UPDATE Shipment
SET status = 'outfordelivery', updated_at = CURRENT_TIMESTAMP
WHERE company_id = $1 AND status = 'intransit' AND outfordelivery_time <= $2
RETURNING tracking_id, status AS new_status, user_jid, recipient_email
`

type TransitionStatusToOutForDeliveryParams struct {
	CompanyID          uuid.NullUUID `json:"company_id"`
	OutfordeliveryTime sql.NullTime  `json:"outfordelivery_time"`
}

type TransitionStatusToOutForDeliveryRow struct {
	TrackingID     string         `json:"tracking_id"`
	NewStatus      sql.NullString `json:"new_status"`
	UserJid        string         `json:"user_jid"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) TransitionStatusToOutForDelivery(ctx context.Context, arg TransitionStatusToOutForDeliveryParams) ([]TransitionStatusToOutForDeliveryRow, error) {
	rows, err := q.db.QueryContext(ctx, transitionStatusToOutForDelivery, arg.CompanyID, arg.OutfordeliveryTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionStatusToOutForDeliveryRow
	for rows.Next() {
		var i TransitionStatusToOutForDeliveryRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.NewStatus,
			&i.UserJid,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyAuthStatus = `-- name: UpdateCompanyAuthStatus :exec
UPDATE companies SET auth_status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdateCompanyAuthStatusParams struct {
	ID         uuid.UUID      `json:"id"`
	AuthStatus sql.NullString `json:"auth_status"`
}

func (q *Queries) UpdateCompanyAuthStatus(ctx context.Context, arg UpdateCompanyAuthStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyAuthStatus, arg.ID, arg.AuthStatus)
	return err
}

const updateCompanyOnboarding = `-- name: UpdateCompanyOnboarding :exec
UPDATE companies SET whatsapp_phone = $2, tracking_prefix = $3, auth_status = 'active', updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdateCompanyOnboardingParams struct {
	ID             uuid.UUID      `json:"id"`
	WhatsappPhone  sql.NullString `json:"whatsapp_phone"`
	TrackingPrefix sql.NullString `json:"tracking_prefix"`
}

func (q *Queries) UpdateCompanyOnboarding(ctx context.Context, arg UpdateCompanyOnboardingParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyOnboarding, arg.ID, arg.WhatsappPhone, arg.TrackingPrefix)
	return err
}

const updateCompanySettings = `-- name: UpdateCompanySettings :exec
UPDATE companies SET name = $2, admin_email = $3, logo_url = $4, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdateCompanySettingsParams struct {
	ID         uuid.UUID      `json:"id"`
	Name       sql.NullString `json:"name"`
	AdminEmail string         `json:"admin_email"`
	LogoUrl    sql.NullString `json:"logo_url"`
}

func (q *Queries) UpdateCompanySettings(ctx context.Context, arg UpdateCompanySettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanySettings,
		arg.ID,
		arg.Name,
		arg.AdminEmail,
		arg.LogoUrl,
	)
	return err
}

const updateCompanySubscriptionStatus = `-- name: UpdateCompanySubscriptionStatus :exec
UPDATE companies 
SET subscription_status = $2, 
    subscription_expiry = GREATEST(subscription_expiry, CURRENT_TIMESTAMP) + INTERVAL '30 days',
    updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

type UpdateCompanySubscriptionStatusParams struct {
	ID                 uuid.UUID      `json:"id"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
}

func (q *Queries) UpdateCompanySubscriptionStatus(ctx context.Context, arg UpdateCompanySubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanySubscriptionStatus, arg.ID, arg.SubscriptionStatus)
	return err
}

const updatePlanPrice = `-- name: UpdatePlanPrice :exec
UPDATE plans SET base_price = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdatePlanPriceParams struct {
	ID        string `json:"id"`
	BasePrice int32  `json:"base_price"`
}

func (q *Queries) UpdatePlanPrice(ctx context.Context, arg UpdatePlanPriceParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanPrice, arg.ID, arg.BasePrice)
	return err
}

const updateShipmentDynamic = `-- name: UpdateShipmentDynamic :exec
UPDATE Shipment
SET 
  sender_name = COALESCE(NULLIF($3::text, ''), sender_name),
  sender_phone = COALESCE(NULLIF($4::text, ''), sender_phone),
  origin = COALESCE(NULLIF($5::text, ''), origin),
  recipient_name = COALESCE(NULLIF($6::text, ''), recipient_name),
  recipient_phone = COALESCE(NULLIF($7::text, ''), recipient_phone),
  recipient_email = COALESCE(NULLIF($8::text, ''), recipient_email),
  recipient_id = COALESCE(NULLIF($9::text, ''), recipient_id),
  recipient_address = COALESCE(NULLIF($10::text, ''), recipient_address),
  destination = COALESCE(NULLIF($11::text, ''), destination),
  cargo_type = COALESCE(NULLIF($12::text, ''), cargo_type),
  scheduled_transit_time = COALESCE($13::timestamp, scheduled_transit_time),
  expected_delivery_time = COALESCE($14::timestamp, expected_delivery_time),
  outfordelivery_time = COALESCE($15::timestamp, outfordelivery_time),
  status = COALESCE(NULLIF($16::text, ''), status),
  updated_at = CURRENT_TIMESTAMP
WHERE company_id = $1 AND tracking_id = $2
`

type UpdateShipmentDynamicParams struct {
	CompanyID  uuid.NullUUID `json:"company_id"`
	TrackingID string        `json:"tracking_id"`
	Column3    string        `json:"column_3"`
	Column4    string        `json:"column_4"`
	Column5    string        `json:"column_5"`
	Column6    string        `json:"column_6"`
	Column7    string        `json:"column_7"`
	Column8    string        `json:"column_8"`
	Column9    string        `json:"column_9"`
	Column10   string        `json:"column_10"`
	Column11   string        `json:"column_11"`
	Column12   string        `json:"column_12"`
	Column13   time.Time     `json:"column_13"`
	Column14   time.Time     `json:"column_14"`
	Column15   time.Time     `json:"column_15"`
	Column16   string        `json:"column_16"`
}

func (q *Queries) UpdateShipmentDynamic(ctx context.Context, arg UpdateShipmentDynamicParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentDynamic,
		arg.CompanyID,
		arg.TrackingID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
	)
	return err
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :exec
UPDATE Shipment SET status = $3, destination = $4, updated_at = CURRENT_TIMESTAMP WHERE company_id = $1 AND tracking_id = $2
`

type UpdateShipmentStatusParams struct {
	CompanyID   uuid.NullUUID  `json:"company_id"`
	TrackingID  string         `json:"tracking_id"`
	Status      sql.NullString `json:"status"`
	Destination sql.NullString `json:"destination"`
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentStatus,
		arg.CompanyID,
		arg.TrackingID,
		arg.Status,
		arg.Destination,
	)
	return err
}
