CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY,
    company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
    reference TEXT UNIQUE NOT NULL,
    amount DOUBLE PRECISION,
    status TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
