// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Groupauthority struct {
	Jid          string       `json:"jid"`
	IsAuthorized bool         `json:"is_authorized"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Shipment struct {
	TrackingID           string          `json:"tracking_id"`
	UserJid              string          `json:"user_jid"`
	Status               sql.NullString  `json:"status"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	ScheduledTransitTime sql.NullTime    `json:"scheduled_transit_time"`
	OutfordeliveryTime   sql.NullTime    `json:"outfordelivery_time"`
	ExpectedDeliveryTime sql.NullTime    `json:"expected_delivery_time"`
	SenderTimezone       sql.NullString  `json:"sender_timezone"`
	RecipientTimezone    sql.NullString  `json:"recipient_timezone"`
	SenderName           sql.NullString  `json:"sender_name"`
	SenderPhone          sql.NullString  `json:"sender_phone"`
	Origin               sql.NullString  `json:"origin"`
	RecipientName        sql.NullString  `json:"recipient_name"`
	RecipientPhone       sql.NullString  `json:"recipient_phone"`
	RecipientEmail       sql.NullString  `json:"recipient_email"`
	RecipientID          sql.NullString  `json:"recipient_id"`
	RecipientAddress     sql.NullString  `json:"recipient_address"`
	Destination          sql.NullString  `json:"destination"`
	CargoType            sql.NullString  `json:"cargo_type"`
	Weight               sql.NullFloat64 `json:"weight"`
	Cost                 sql.NullFloat64 `json:"cost"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}

type Systemconfig struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Userpreference struct {
	Jid       string       `json:"jid"`
	Language  string       `json:"language"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
