// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	BulkUpdateStatus(ctx context.Context, arg BulkUpdateStatusParams) error
	CountAuthorizedGroups(ctx context.Context) (int64, error)
	CountCreatedSince(ctx context.Context, createdAt sql.NullTime) (int64, error)
	CountDeliveredSince(ctx context.Context, updatedAt sql.NullTime) (int64, error)
	CountShipments(ctx context.Context) (int64, error)
	CountShipmentsByStatus(ctx context.Context) (CountShipmentsByStatusRow, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) error
	DeleteDeliveredShipments(ctx context.Context) error
	DeleteShipment(ctx context.Context, trackingID string) error
	FindSimilarShipment(ctx context.Context, arg FindSimilarShipmentParams) (string, error)
	GetAuthorizedGroups(ctx context.Context) ([]string, error)
	GetGroupAuthority(ctx context.Context, jid string) (GetGroupAuthorityRow, error)
	GetLastShipmentIDForUser(ctx context.Context, userJid string) (string, error)
	GetRecentEvents(ctx context.Context, limit int32) ([]Telemetry, error)
	GetShipment(ctx context.Context, trackingID string) (Shipment, error)
	GetSystemConfig(ctx context.Context, key string) (string, error)
	GetTelemetryStats(ctx context.Context, createdAt sql.NullTime) ([]GetTelemetryStatsRow, error)
	GetUserLanguage(ctx context.Context, jid string) (string, error)
	HasAuthorizedGroups(ctx context.Context) (int64, error)
	ListAllShipments(ctx context.Context) ([]Shipment, error)
	ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error)
	RecordEvent(ctx context.Context, arg RecordEventParams) error
	RunAgedCleanup(ctx context.Context, arg RunAgedCleanupParams) error
	SetGroupAuthority(ctx context.Context, arg SetGroupAuthorityParams) error
	SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) error
	SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error
	TransitionStatusToDelivered(ctx context.Context, expectedDeliveryTime sql.NullTime) ([]TransitionStatusToDeliveredRow, error)
	TransitionStatusToIntransit(ctx context.Context, scheduledTransitTime sql.NullTime) ([]TransitionStatusToIntransitRow, error)
	TransitionStatusToOutForDelivery(ctx context.Context, outfordeliveryTime sql.NullTime) ([]TransitionStatusToOutForDeliveryRow, error)
	UpdateShipmentFieldCargoType(ctx context.Context, arg UpdateShipmentFieldCargoTypeParams) error
	UpdateShipmentFieldDestination(ctx context.Context, arg UpdateShipmentFieldDestinationParams) error
	UpdateShipmentFieldExpectedDeliveryTime(ctx context.Context, arg UpdateShipmentFieldExpectedDeliveryTimeParams) error
	UpdateShipmentFieldOrigin(ctx context.Context, arg UpdateShipmentFieldOriginParams) error
	UpdateShipmentFieldOutfordeliveryTime(ctx context.Context, arg UpdateShipmentFieldOutfordeliveryTimeParams) error
	UpdateShipmentFieldRecipientAddress(ctx context.Context, arg UpdateShipmentFieldRecipientAddressParams) error
	UpdateShipmentFieldRecipientEmail(ctx context.Context, arg UpdateShipmentFieldRecipientEmailParams) error
	UpdateShipmentFieldRecipientID(ctx context.Context, arg UpdateShipmentFieldRecipientIDParams) error
	UpdateShipmentFieldRecipientName(ctx context.Context, arg UpdateShipmentFieldRecipientNameParams) error
	UpdateShipmentFieldRecipientPhone(ctx context.Context, arg UpdateShipmentFieldRecipientPhoneParams) error
	UpdateShipmentFieldScheduledTransitTime(ctx context.Context, arg UpdateShipmentFieldScheduledTransitTimeParams) error
	UpdateShipmentFieldSenderName(ctx context.Context, arg UpdateShipmentFieldSenderNameParams) error
	UpdateShipmentFieldSenderPhone(ctx context.Context, arg UpdateShipmentFieldSenderPhoneParams) error
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) error
}

var _ Querier = (*Queries)(nil)
