// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const bulkUpdateStatus = `-- name: BulkUpdateStatus :exec
UPDATE Shipment
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE tracking_id = ANY($1::text[])
`

type BulkUpdateStatusParams struct {
	Column1 []string       `json:"column_1"`
	Status  sql.NullString `json:"status"`
}

func (q *Queries) BulkUpdateStatus(ctx context.Context, arg BulkUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateStatus, pq.Array(arg.Column1), arg.Status)
	return err
}

const countAuthorizedGroups = `-- name: CountAuthorizedGroups :one
SELECT COUNT(*) FROM GroupAuthority WHERE is_authorized = true
`

func (q *Queries) CountAuthorizedGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthorizedGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCreatedSince = `-- name: CountCreatedSince :one
SELECT COUNT(*) FROM Shipment WHERE created_at >= $1
`

func (q *Queries) CountCreatedSince(ctx context.Context, createdAt sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveredSince = `-- name: CountDeliveredSince :one
SELECT COUNT(*) FROM Shipment WHERE status = 'delivered' AND updated_at >= $1
`

func (q *Queries) CountDeliveredSince(ctx context.Context, updatedAt sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveredSince, updatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipments = `-- name: CountShipments :one
SELECT COUNT(*) FROM Shipment
`

func (q *Queries) CountShipments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShipments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipmentsByStatus = `-- name: CountShipmentsByStatus :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE status = 'intransit') AS intransit,
    COUNT(*) FILTER (WHERE status = 'outfordelivery') AS outfordelivery,
    COUNT(*) FILTER (WHERE status = 'delivered') AS delivered,
    COUNT(*) FILTER (WHERE status = 'canceled') AS canceled
FROM Shipment
`

type CountShipmentsByStatusRow struct {
	Total          int64 `json:"total"`
	Pending        int64 `json:"pending"`
	Intransit      int64 `json:"intransit"`
	Outfordelivery int64 `json:"outfordelivery"`
	Delivered      int64 `json:"delivered"`
	Canceled       int64 `json:"canceled"`
}

func (q *Queries) CountShipmentsByStatus(ctx context.Context) (CountShipmentsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countShipmentsByStatus)
	var i CountShipmentsByStatusRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Intransit,
		&i.Outfordelivery,
		&i.Delivered,
		&i.Canceled,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :exec
INSERT INTO Shipment (
    tracking_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
)
`

type CreateShipmentParams struct {
	TrackingID           string          `json:"tracking_id"`
	UserJid              string          `json:"user_jid"`
	Status               sql.NullString  `json:"status"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	ScheduledTransitTime sql.NullTime    `json:"scheduled_transit_time"`
	OutfordeliveryTime   sql.NullTime    `json:"outfordelivery_time"`
	ExpectedDeliveryTime sql.NullTime    `json:"expected_delivery_time"`
	SenderTimezone       sql.NullString  `json:"sender_timezone"`
	RecipientTimezone    sql.NullString  `json:"recipient_timezone"`
	SenderName           sql.NullString  `json:"sender_name"`
	SenderPhone          sql.NullString  `json:"sender_phone"`
	Origin               sql.NullString  `json:"origin"`
	RecipientName        sql.NullString  `json:"recipient_name"`
	RecipientPhone       sql.NullString  `json:"recipient_phone"`
	RecipientEmail       sql.NullString  `json:"recipient_email"`
	RecipientID          sql.NullString  `json:"recipient_id"`
	RecipientAddress     sql.NullString  `json:"recipient_address"`
	Destination          sql.NullString  `json:"destination"`
	CargoType            sql.NullString  `json:"cargo_type"`
	Weight               sql.NullFloat64 `json:"weight"`
	Cost                 sql.NullFloat64 `json:"cost"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) error {
	_, err := q.db.ExecContext(ctx, createShipment,
		arg.TrackingID,
		arg.UserJid,
		arg.Status,
		arg.CreatedAt,
		arg.ScheduledTransitTime,
		arg.OutfordeliveryTime,
		arg.ExpectedDeliveryTime,
		arg.SenderTimezone,
		arg.RecipientTimezone,
		arg.SenderName,
		arg.SenderPhone,
		arg.Origin,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.RecipientEmail,
		arg.RecipientID,
		arg.RecipientAddress,
		arg.Destination,
		arg.CargoType,
		arg.Weight,
		arg.Cost,
		arg.UpdatedAt,
	)
	return err
}

const deleteDeliveredShipments = `-- name: DeleteDeliveredShipments :exec
DELETE FROM Shipment WHERE status = 'delivered'
`

func (q *Queries) DeleteDeliveredShipments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveredShipments)
	return err
}

const deleteShipment = `-- name: DeleteShipment :exec
DELETE FROM Shipment WHERE tracking_id = $1
`

func (q *Queries) DeleteShipment(ctx context.Context, trackingID string) error {
	_, err := q.db.ExecContext(ctx, deleteShipment, trackingID)
	return err
}

const findSimilarShipment = `-- name: FindSimilarShipment :one
SELECT tracking_id FROM Shipment 
WHERE user_jid = $1 
AND (
    (recipient_phone = $2 AND $2 != '') OR 
    (recipient_email = $3 AND $3 != '') OR 
    (recipient_id = $4 AND $4 != '')
)
ORDER BY created_at DESC LIMIT 1
`

type FindSimilarShipmentParams struct {
	UserJid        string         `json:"user_jid"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
	RecipientEmail sql.NullString `json:"recipient_email"`
	RecipientID    sql.NullString `json:"recipient_id"`
}

func (q *Queries) FindSimilarShipment(ctx context.Context, arg FindSimilarShipmentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findSimilarShipment,
		arg.UserJid,
		arg.RecipientPhone,
		arg.RecipientEmail,
		arg.RecipientID,
	)
	var tracking_id string
	err := row.Scan(&tracking_id)
	return tracking_id, err
}

const getAuthorizedGroups = `-- name: GetAuthorizedGroups :many
SELECT jid FROM GroupAuthority WHERE is_authorized = true
`

func (q *Queries) GetAuthorizedGroups(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorizedGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jid string
		if err := rows.Scan(&jid); err != nil {
			return nil, err
		}
		items = append(items, jid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupAuthority = `-- name: GetGroupAuthority :one
SELECT is_authorized, updated_at FROM GroupAuthority WHERE jid = $1
`

type GetGroupAuthorityRow struct {
	IsAuthorized bool         `json:"is_authorized"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetGroupAuthority(ctx context.Context, jid string) (GetGroupAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupAuthority, jid)
	var i GetGroupAuthorityRow
	err := row.Scan(&i.IsAuthorized, &i.UpdatedAt)
	return i, err
}

const getLastShipmentIDForUser = `-- name: GetLastShipmentIDForUser :one
SELECT tracking_id FROM Shipment WHERE user_jid = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastShipmentIDForUser(ctx context.Context, userJid string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastShipmentIDForUser, userJid)
	var tracking_id string
	err := row.Scan(&tracking_id)
	return tracking_id, err
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, event_type, metadata, created_at FROM Telemetry
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentEvents(ctx context.Context, limit int32) ([]Telemetry, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Telemetry
	for rows.Next() {
		var i Telemetry
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShipment = `-- name: GetShipment :one
SELECT tracking_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at FROM Shipment WHERE tracking_id = $1
`

func (q *Queries) GetShipment(ctx context.Context, trackingID string) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, getShipment, trackingID)
	var i Shipment
	err := row.Scan(
		&i.TrackingID,
		&i.UserJid,
		&i.Status,
		&i.CreatedAt,
		&i.ScheduledTransitTime,
		&i.OutfordeliveryTime,
		&i.ExpectedDeliveryTime,
		&i.SenderTimezone,
		&i.RecipientTimezone,
		&i.SenderName,
		&i.SenderPhone,
		&i.Origin,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.RecipientEmail,
		&i.RecipientID,
		&i.RecipientAddress,
		&i.Destination,
		&i.CargoType,
		&i.Weight,
		&i.Cost,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT value FROM SystemConfig WHERE key = $1
`

func (q *Queries) GetSystemConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSystemConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getTelemetryStats = `-- name: GetTelemetryStats :many
SELECT event_type, COUNT(*) as count
FROM Telemetry
WHERE created_at >= $1
GROUP BY event_type
`

type GetTelemetryStatsRow struct {
	EventType string `json:"event_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetTelemetryStats(ctx context.Context, createdAt sql.NullTime) ([]GetTelemetryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTelemetryStats, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryStatsRow
	for rows.Next() {
		var i GetTelemetryStatsRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLanguage = `-- name: GetUserLanguage :one
SELECT language FROM UserPreference WHERE jid = $1
`

func (q *Queries) GetUserLanguage(ctx context.Context, jid string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserLanguage, jid)
	var language string
	err := row.Scan(&language)
	return language, err
}

const hasAuthorizedGroups = `-- name: HasAuthorizedGroups :one
SELECT COUNT(*) FROM GroupAuthority WHERE is_authorized = true
`

func (q *Queries) HasAuthorizedGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAuthorizedGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllShipments = `-- name: ListAllShipments :many
SELECT tracking_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at FROM Shipment ORDER BY created_at DESC
`

func (q *Queries) ListAllShipments(ctx context.Context) ([]Shipment, error) {
	rows, err := q.db.QueryContext(ctx, listAllShipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.TrackingID,
			&i.UserJid,
			&i.Status,
			&i.CreatedAt,
			&i.ScheduledTransitTime,
			&i.OutfordeliveryTime,
			&i.ExpectedDeliveryTime,
			&i.SenderTimezone,
			&i.RecipientTimezone,
			&i.SenderName,
			&i.SenderPhone,
			&i.Origin,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.RecipientEmail,
			&i.RecipientID,
			&i.RecipientAddress,
			&i.Destination,
			&i.CargoType,
			&i.Weight,
			&i.Cost,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT tracking_id, user_jid, status, created_at, scheduled_transit_time, outfordelivery_time, expected_delivery_time, sender_timezone, recipient_timezone, sender_name, sender_phone, origin, recipient_name, recipient_phone, recipient_email, recipient_id, recipient_address, destination, cargo_type, weight, cost, updated_at FROM Shipment ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListShipmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]Shipment, error) {
	rows, err := q.db.QueryContext(ctx, listShipments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.TrackingID,
			&i.UserJid,
			&i.Status,
			&i.CreatedAt,
			&i.ScheduledTransitTime,
			&i.OutfordeliveryTime,
			&i.ExpectedDeliveryTime,
			&i.SenderTimezone,
			&i.RecipientTimezone,
			&i.SenderName,
			&i.SenderPhone,
			&i.Origin,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.RecipientEmail,
			&i.RecipientID,
			&i.RecipientAddress,
			&i.Destination,
			&i.CargoType,
			&i.Weight,
			&i.Cost,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :exec
INSERT INTO Telemetry (event_type, metadata, created_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
`

type RecordEventParams struct {
	EventType string                `json:"event_type"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.ExecContext(ctx, recordEvent, arg.EventType, arg.Metadata)
	return err
}

const runAgedCleanup = `-- name: RunAgedCleanup :exec
DELETE FROM Shipment 
WHERE (status = 'delivered' AND updated_at < $1) OR (created_at < $2)
`

type RunAgedCleanupParams struct {
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) RunAgedCleanup(ctx context.Context, arg RunAgedCleanupParams) error {
	_, err := q.db.ExecContext(ctx, runAgedCleanup, arg.UpdatedAt, arg.CreatedAt)
	return err
}

const setGroupAuthority = `-- name: SetGroupAuthority :exec
INSERT INTO GroupAuthority (jid, is_authorized, updated_at) 
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT(jid) DO UPDATE SET is_authorized = EXCLUDED.is_authorized, updated_at = CURRENT_TIMESTAMP
`

type SetGroupAuthorityParams struct {
	Jid          string `json:"jid"`
	IsAuthorized bool   `json:"is_authorized"`
}

func (q *Queries) SetGroupAuthority(ctx context.Context, arg SetGroupAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, setGroupAuthority, arg.Jid, arg.IsAuthorized)
	return err
}

const setSystemConfig = `-- name: SetSystemConfig :exec
INSERT INTO SystemConfig (key, value, updated_at) 
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = EXCLUDED.value, updated_at = CURRENT_TIMESTAMP
`

type SetSystemConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) error {
	_, err := q.db.ExecContext(ctx, setSystemConfig, arg.Key, arg.Value)
	return err
}

const setUserLanguage = `-- name: SetUserLanguage :exec
INSERT INTO UserPreference (jid, language, updated_at) 
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT(jid) DO UPDATE SET language = EXCLUDED.language, updated_at = CURRENT_TIMESTAMP
`

type SetUserLanguageParams struct {
	Jid      string `json:"jid"`
	Language string `json:"language"`
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.ExecContext(ctx, setUserLanguage, arg.Jid, arg.Language)
	return err
}

const transitionStatusToDelivered = `-- name: TransitionStatusToDelivered :many
UPDATE Shipment
SET status = 'delivered', updated_at = CURRENT_TIMESTAMP
WHERE status = 'outfordelivery' AND expected_delivery_time <= $1
RETURNING tracking_id, status AS new_status, user_jid, recipient_email
`

type TransitionStatusToDeliveredRow struct {
	TrackingID     string         `json:"tracking_id"`
	NewStatus      sql.NullString `json:"new_status"`
	UserJid        string         `json:"user_jid"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) TransitionStatusToDelivered(ctx context.Context, expectedDeliveryTime sql.NullTime) ([]TransitionStatusToDeliveredRow, error) {
	rows, err := q.db.QueryContext(ctx, transitionStatusToDelivered, expectedDeliveryTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionStatusToDeliveredRow
	for rows.Next() {
		var i TransitionStatusToDeliveredRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.NewStatus,
			&i.UserJid,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionStatusToIntransit = `-- name: TransitionStatusToIntransit :many
UPDATE Shipment
SET status = 'intransit', updated_at = CURRENT_TIMESTAMP
WHERE status = 'pending' AND scheduled_transit_time <= $1
RETURNING tracking_id, status AS new_status, user_jid, recipient_email
`

type TransitionStatusToIntransitRow struct {
	TrackingID     string         `json:"tracking_id"`
	NewStatus      sql.NullString `json:"new_status"`
	UserJid        string         `json:"user_jid"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) TransitionStatusToIntransit(ctx context.Context, scheduledTransitTime sql.NullTime) ([]TransitionStatusToIntransitRow, error) {
	rows, err := q.db.QueryContext(ctx, transitionStatusToIntransit, scheduledTransitTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionStatusToIntransitRow
	for rows.Next() {
		var i TransitionStatusToIntransitRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.NewStatus,
			&i.UserJid,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionStatusToOutForDelivery = `-- name: TransitionStatusToOutForDelivery :many
UPDATE Shipment
SET status = 'outfordelivery', updated_at = CURRENT_TIMESTAMP
WHERE status = 'intransit' AND outfordelivery_time <= $1
RETURNING tracking_id, status AS new_status, user_jid, recipient_email
`

type TransitionStatusToOutForDeliveryRow struct {
	TrackingID     string         `json:"tracking_id"`
	NewStatus      sql.NullString `json:"new_status"`
	UserJid        string         `json:"user_jid"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) TransitionStatusToOutForDelivery(ctx context.Context, outfordeliveryTime sql.NullTime) ([]TransitionStatusToOutForDeliveryRow, error) {
	rows, err := q.db.QueryContext(ctx, transitionStatusToOutForDelivery, outfordeliveryTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitionStatusToOutForDeliveryRow
	for rows.Next() {
		var i TransitionStatusToOutForDeliveryRow
		if err := rows.Scan(
			&i.TrackingID,
			&i.NewStatus,
			&i.UserJid,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipmentFieldCargoType = `-- name: UpdateShipmentFieldCargoType :exec
UPDATE Shipment SET cargo_type = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldCargoTypeParams struct {
	TrackingID string         `json:"tracking_id"`
	CargoType  sql.NullString `json:"cargo_type"`
}

func (q *Queries) UpdateShipmentFieldCargoType(ctx context.Context, arg UpdateShipmentFieldCargoTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldCargoType, arg.TrackingID, arg.CargoType)
	return err
}

const updateShipmentFieldDestination = `-- name: UpdateShipmentFieldDestination :exec
UPDATE Shipment SET destination = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldDestinationParams struct {
	TrackingID  string         `json:"tracking_id"`
	Destination sql.NullString `json:"destination"`
}

func (q *Queries) UpdateShipmentFieldDestination(ctx context.Context, arg UpdateShipmentFieldDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldDestination, arg.TrackingID, arg.Destination)
	return err
}

const updateShipmentFieldExpectedDeliveryTime = `-- name: UpdateShipmentFieldExpectedDeliveryTime :exec
UPDATE Shipment SET expected_delivery_time = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldExpectedDeliveryTimeParams struct {
	TrackingID           string       `json:"tracking_id"`
	ExpectedDeliveryTime sql.NullTime `json:"expected_delivery_time"`
}

func (q *Queries) UpdateShipmentFieldExpectedDeliveryTime(ctx context.Context, arg UpdateShipmentFieldExpectedDeliveryTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldExpectedDeliveryTime, arg.TrackingID, arg.ExpectedDeliveryTime)
	return err
}

const updateShipmentFieldOrigin = `-- name: UpdateShipmentFieldOrigin :exec
UPDATE Shipment SET origin = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldOriginParams struct {
	TrackingID string         `json:"tracking_id"`
	Origin     sql.NullString `json:"origin"`
}

func (q *Queries) UpdateShipmentFieldOrigin(ctx context.Context, arg UpdateShipmentFieldOriginParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldOrigin, arg.TrackingID, arg.Origin)
	return err
}

const updateShipmentFieldOutfordeliveryTime = `-- name: UpdateShipmentFieldOutfordeliveryTime :exec
UPDATE Shipment SET outfordelivery_time = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldOutfordeliveryTimeParams struct {
	TrackingID         string       `json:"tracking_id"`
	OutfordeliveryTime sql.NullTime `json:"outfordelivery_time"`
}

func (q *Queries) UpdateShipmentFieldOutfordeliveryTime(ctx context.Context, arg UpdateShipmentFieldOutfordeliveryTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldOutfordeliveryTime, arg.TrackingID, arg.OutfordeliveryTime)
	return err
}

const updateShipmentFieldRecipientAddress = `-- name: UpdateShipmentFieldRecipientAddress :exec
UPDATE Shipment SET recipient_address = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldRecipientAddressParams struct {
	TrackingID       string         `json:"tracking_id"`
	RecipientAddress sql.NullString `json:"recipient_address"`
}

func (q *Queries) UpdateShipmentFieldRecipientAddress(ctx context.Context, arg UpdateShipmentFieldRecipientAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldRecipientAddress, arg.TrackingID, arg.RecipientAddress)
	return err
}

const updateShipmentFieldRecipientEmail = `-- name: UpdateShipmentFieldRecipientEmail :exec
UPDATE Shipment SET recipient_email = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldRecipientEmailParams struct {
	TrackingID     string         `json:"tracking_id"`
	RecipientEmail sql.NullString `json:"recipient_email"`
}

func (q *Queries) UpdateShipmentFieldRecipientEmail(ctx context.Context, arg UpdateShipmentFieldRecipientEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldRecipientEmail, arg.TrackingID, arg.RecipientEmail)
	return err
}

const updateShipmentFieldRecipientID = `-- name: UpdateShipmentFieldRecipientID :exec
UPDATE Shipment SET recipient_id = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldRecipientIDParams struct {
	TrackingID  string         `json:"tracking_id"`
	RecipientID sql.NullString `json:"recipient_id"`
}

func (q *Queries) UpdateShipmentFieldRecipientID(ctx context.Context, arg UpdateShipmentFieldRecipientIDParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldRecipientID, arg.TrackingID, arg.RecipientID)
	return err
}

const updateShipmentFieldRecipientName = `-- name: UpdateShipmentFieldRecipientName :exec
UPDATE Shipment SET recipient_name = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldRecipientNameParams struct {
	TrackingID    string         `json:"tracking_id"`
	RecipientName sql.NullString `json:"recipient_name"`
}

func (q *Queries) UpdateShipmentFieldRecipientName(ctx context.Context, arg UpdateShipmentFieldRecipientNameParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldRecipientName, arg.TrackingID, arg.RecipientName)
	return err
}

const updateShipmentFieldRecipientPhone = `-- name: UpdateShipmentFieldRecipientPhone :exec
UPDATE Shipment SET recipient_phone = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldRecipientPhoneParams struct {
	TrackingID     string         `json:"tracking_id"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
}

func (q *Queries) UpdateShipmentFieldRecipientPhone(ctx context.Context, arg UpdateShipmentFieldRecipientPhoneParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldRecipientPhone, arg.TrackingID, arg.RecipientPhone)
	return err
}

const updateShipmentFieldScheduledTransitTime = `-- name: UpdateShipmentFieldScheduledTransitTime :exec
UPDATE Shipment SET scheduled_transit_time = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldScheduledTransitTimeParams struct {
	TrackingID           string       `json:"tracking_id"`
	ScheduledTransitTime sql.NullTime `json:"scheduled_transit_time"`
}

func (q *Queries) UpdateShipmentFieldScheduledTransitTime(ctx context.Context, arg UpdateShipmentFieldScheduledTransitTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldScheduledTransitTime, arg.TrackingID, arg.ScheduledTransitTime)
	return err
}

const updateShipmentFieldSenderName = `-- name: UpdateShipmentFieldSenderName :exec
UPDATE Shipment SET sender_name = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldSenderNameParams struct {
	TrackingID string         `json:"tracking_id"`
	SenderName sql.NullString `json:"sender_name"`
}

func (q *Queries) UpdateShipmentFieldSenderName(ctx context.Context, arg UpdateShipmentFieldSenderNameParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldSenderName, arg.TrackingID, arg.SenderName)
	return err
}

const updateShipmentFieldSenderPhone = `-- name: UpdateShipmentFieldSenderPhone :exec
UPDATE Shipment SET sender_phone = $2, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentFieldSenderPhoneParams struct {
	TrackingID  string         `json:"tracking_id"`
	SenderPhone sql.NullString `json:"sender_phone"`
}

func (q *Queries) UpdateShipmentFieldSenderPhone(ctx context.Context, arg UpdateShipmentFieldSenderPhoneParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentFieldSenderPhone, arg.TrackingID, arg.SenderPhone)
	return err
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :exec
UPDATE Shipment SET status = $2, destination = $3, updated_at = CURRENT_TIMESTAMP WHERE tracking_id = $1
`

type UpdateShipmentStatusParams struct {
	TrackingID  string         `json:"tracking_id"`
	Status      sql.NullString `json:"status"`
	Destination sql.NullString `json:"destination"`
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateShipmentStatus, arg.TrackingID, arg.Status, arg.Destination)
	return err
}
